### ISSUE TITLE
"On" parameter in params.txt not respected

### ISSUE THREAD

**Issue by GearheadLydia** [mod-loader/engine-sim-modloader#10]
Since version 0.05a, the "on" parameter has not been respected in params.txt. This has broken the sound exporter for BeamNG and other games.

(Thank you for updating Mod Loader pretty quickly with the new changes, and sorry to bother you!)

**Comment by DDev247** [comment]
Noticed that, and fixed it in a new update coming out soon.

**Comment by DDev247** [comment]
Fixed in 0.0.51a
